apiVersion: v1
kind: Service
metadata:
  name: http-error-403
  namespace: file-uploader
spec:
  ports:
  - port: 80
    targetPort: 80
  # No selector means this service has no endpoints,
  # causing the Ingress to return a 503 or 404 (effectively blocking the path).
